homeassistant:
  auth_providers:
    - type: homeassistant

http:
  server_port: 18123

frontend:
config:
onboarding:
recorder:
energy:

logger:
  default: info
  logs:
    custom_components.wa_synergy: debug
